source: .

exclude: [NO_GIT, Gemfile, Gemfile.lock]

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false
  toc_levels: 2..4

gems:
  - jekyll-compass
  - singularitygs
  - breakpoint

defaults:
  -
    scope:
      path: ''
    values:
      layout: layout

